version : '3'
services:
  stunnel:
    build:
      dockerfile : Dockerfile
      context: 'Stunnel'
    restart: always
    ports:
      - '443:443'
    ulimits:
      nofile:
        soft: 1024000
        hard: 1024000
  socks:
    build:
      dockerfile : Dockerfile
      context: 'Dante'
    restart: always
    ulimits:
      nofile:
        soft: 1024000
        hard: 1024000
