version : '3'
services: 
  stunnel:
    build:
      dockerfile : Dockerfile
      context: 'Stunnel'
    restart: always
    ports:
      - '443:443'
  socks:
    build:
      dockerfile : Dockerfile
      context: 'Dante'
    restart: always

